name: Azure Pipelines
variables:
  python.version: '3.7.6'
stages:
- stage: provision_infrastructure
  jobs:
  - job:  provision_infrastructure
    displayName: Provision Infrastructure
    pool:
      name: Hosted Ubuntu 1604
    steps:
    - task: DownloadSecureFile@1
      displayName: Download terraform.tfvars 
      inputs:
        secureFile: 'terraform.tfvars'

    - task: Bash@3
      displayName: Copy terraform.tfvars 
      inputs:
          targetType: 'inline'
          script: cp $(Agent.TempDirectory)/terraform.tfvars $(System.DefaultWorkingDirectory)/terraform
           
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
          terraformVersion: 'v0.15.4'
      
    - task: TerraformTaskV2@2
      displayName: "Terraform Init"
      inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Project3'
          backendAzureRmResourceGroupName: 'project3'
          backendAzureRmStorageAccountName: 'daxproj3tf'
          backendAzureRmContainerName: 'terraform'
          backendAzureRmKey: 'terraform.tfstate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      
    - task: TerraformTaskV2@2
      inputs:
          provider: 'azurerm'
          command: 'validate'
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: |
          -auto-approve 
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceNameAzureRM: 'Project3'
